/** Shared by the worker parser and the native host's closed environment contract. */
export const CONNECTED_WORKER_ENV = Object.freeze({
  host: "GOATCITADEL_CONNECTED_WORKER_HOST",
  port: "GOATCITADEL_CONNECTED_WORKER_PORT",
  clientCertificateFile: "GOATCITADEL_CONNECTED_WORKER_CLIENT_CERT_FILE",
  clientKeyFile: "GOATCITADEL_CONNECTED_WORKER_CLIENT_KEY_FILE",
  protectedKeyFile: "GOATCITADEL_CONNECTED_WORKER_PROTECTED_KEY_FILE",
  trustAnchorFile: "GOATCITADEL_CONNECTED_WORKER_CA_FILE",
  ticketFile: "GOATCITADEL_CONNECTED_WORKER_TICKET_FILE",
  stateDir: "GOATCITADEL_CONNECTED_WORKER_STATE_DIR",
  reportFile: "GOATCITADEL_CONNECTED_WORKER_REPORT_FILE",
  runId: "GOATCITADEL_CONNECTED_WORKER_RUN_ID",
  stopAfter: "GOATCITADEL_CONNECTED_WORKER_STOP_AFTER",
  executionMode: "GOATCITADEL_CONNECTED_WORKER_EXECUTION_MODE",
  runMode: "GOATCITADEL_CONNECTED_WORKER_RUN_MODE",
  meshRegistryFile: "GOATCITADEL_CONNECTED_WORKER_MESH_REGISTRY_FILE",
  meshRegistrySha256: "GOATCITADEL_CONNECTED_WORKER_MESH_REGISTRY_SHA256",
  hostControl: "GOATCITADEL_CONNECTED_WORKER_HOST_CONTROL",
} as const);

// Lifecycle notification only. This value conveys no admission or tool authority.
export const WORKER_HOST_CONTROL_PROTOCOL = "stdin-close-v1";
