import type { DatabaseClient } from "./db.js";

export const CHANNEL_GUIDED_SETUP_POSTGRES_SQL = `
CREATE TABLE IF NOT EXISTS channel_setup_evidence (
  sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evidence_id TEXT UNIQUE NOT NULL,
  catalog_id TEXT NOT NULL,
  draft_id TEXT NOT NULL,
  draft_revision INTEGER NOT NULL CHECK(draft_revision >= 1),
  connection_id TEXT,
  connection_revision TEXT,
  phase TEXT NOT NULL CHECK(phase IN ('test', 'acknowledgement', 'activation')),
  status TEXT NOT NULL CHECK(status IN ('idle', 'ok', 'warn', 'error')),
  checked_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  payload_json TEXT NOT NULL CHECK(length(payload_json) <= 65536)
);
CREATE INDEX IF NOT EXISTS idx_channel_setup_evidence_draft
  ON channel_setup_evidence(draft_id, sequence DESC);
CREATE INDEX IF NOT EXISTS idx_channel_setup_evidence_connection
  ON channel_setup_evidence(connection_id, sequence DESC);
CREATE TABLE IF NOT EXISTS channel_oauth_attempts (
  attempt_id TEXT PRIMARY KEY,
  revision INTEGER NOT NULL DEFAULT 1 CHECK(revision >= 1),
  provider TEXT NOT NULL,
  installation_id TEXT NOT NULL,
  workspace_id TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  draft_id TEXT NOT NULL,
  draft_revision INTEGER NOT NULL CHECK(draft_revision >= 1),
  connection_id TEXT,
  connection_revision TEXT,
  state_hash TEXT UNIQUE NOT NULL,
  origin TEXT,
  status TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  install_json TEXT,
  secret_refs_json TEXT NOT NULL DEFAULT '{}',
  adopted_draft_revision INTEGER,
  failure_code TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_channel_oauth_attempts_expiry ON channel_oauth_attempts(status, expires_at);
CREATE INDEX IF NOT EXISTS idx_channel_oauth_attempts_draft ON channel_oauth_attempts(draft_id, created_at DESC);

CREATE OR REPLACE FUNCTION gc_channel_setup_evidence_immutable() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'Channel setup evidence is immutable' USING ERRCODE = '23514'; END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trg_channel_setup_evidence_no_update ON channel_setup_evidence;
CREATE TRIGGER trg_channel_setup_evidence_no_update BEFORE UPDATE OR DELETE ON channel_setup_evidence
FOR EACH ROW EXECUTE FUNCTION gc_channel_setup_evidence_immutable();
CREATE OR REPLACE FUNCTION gc_channel_oauth_attempt_bindings() RETURNS trigger AS $$
BEGIN
  IF NEW.attempt_id IS DISTINCT FROM OLD.attempt_id OR NEW.provider IS DISTINCT FROM OLD.provider
    OR NEW.installation_id IS DISTINCT FROM OLD.installation_id OR NEW.workspace_id IS DISTINCT FROM OLD.workspace_id
    OR NEW.actor_id IS DISTINCT FROM OLD.actor_id OR NEW.draft_id IS DISTINCT FROM OLD.draft_id
    OR NEW.draft_revision IS DISTINCT FROM OLD.draft_revision OR NEW.connection_id IS DISTINCT FROM OLD.connection_id
    OR NEW.connection_revision IS DISTINCT FROM OLD.connection_revision OR NEW.state_hash IS DISTINCT FROM OLD.state_hash
    OR NEW.origin IS DISTINCT FROM OLD.origin OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
    OR NEW.created_at IS DISTINCT FROM OLD.created_at OR NEW.revision <> OLD.revision + 1 THEN
    RAISE EXCEPTION 'Channel OAuth attempt authority cannot change' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trg_channel_oauth_attempts_bindings ON channel_oauth_attempts;
CREATE TRIGGER trg_channel_oauth_attempts_bindings BEFORE UPDATE ON channel_oauth_attempts
FOR EACH ROW EXECUTE FUNCTION gc_channel_oauth_attempt_bindings();
`;

export function createChannelGuidedSetupSchema(db: Pick<DatabaseClient, "exec">): void {
  db.exec(`
CREATE TABLE IF NOT EXISTS channel_setup_evidence (
  sequence INTEGER PRIMARY KEY AUTOINCREMENT,
  evidence_id TEXT UNIQUE NOT NULL,
  catalog_id TEXT NOT NULL,
  draft_id TEXT NOT NULL,
  draft_revision INTEGER NOT NULL CHECK(draft_revision >= 1),
  connection_id TEXT,
  connection_revision TEXT,
  phase TEXT NOT NULL CHECK(phase IN ('test', 'acknowledgement', 'activation')),
  status TEXT NOT NULL CHECK(status IN ('idle', 'ok', 'warn', 'error')),
  checked_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  payload_json TEXT NOT NULL CHECK(length(payload_json) <= 65536)
);
CREATE INDEX IF NOT EXISTS idx_channel_setup_evidence_draft
  ON channel_setup_evidence(draft_id, sequence DESC);
CREATE INDEX IF NOT EXISTS idx_channel_setup_evidence_connection
  ON channel_setup_evidence(connection_id, sequence DESC);
CREATE TABLE IF NOT EXISTS channel_oauth_attempts (
  attempt_id TEXT PRIMARY KEY,
  revision INTEGER NOT NULL DEFAULT 1 CHECK(revision >= 1),
  provider TEXT NOT NULL,
  installation_id TEXT NOT NULL,
  workspace_id TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  draft_id TEXT NOT NULL,
  draft_revision INTEGER NOT NULL CHECK(draft_revision >= 1),
  connection_id TEXT,
  connection_revision TEXT,
  state_hash TEXT UNIQUE NOT NULL,
  origin TEXT,
  status TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  install_json TEXT,
  secret_refs_json TEXT NOT NULL DEFAULT '{}',
  adopted_draft_revision INTEGER,
  failure_code TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_channel_oauth_attempts_expiry ON channel_oauth_attempts(status, expires_at);
CREATE INDEX IF NOT EXISTS idx_channel_oauth_attempts_draft ON channel_oauth_attempts(draft_id, created_at DESC);

CREATE TRIGGER IF NOT EXISTS trg_channel_setup_evidence_no_update BEFORE UPDATE ON channel_setup_evidence
BEGIN SELECT RAISE(ABORT, 'Channel setup evidence is immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_channel_setup_evidence_no_delete BEFORE DELETE ON channel_setup_evidence
BEGIN SELECT RAISE(ABORT, 'Channel setup evidence is immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_channel_oauth_attempts_bindings BEFORE UPDATE ON channel_oauth_attempts
WHEN NEW.attempt_id IS NOT OLD.attempt_id OR NEW.provider IS NOT OLD.provider
  OR NEW.installation_id IS NOT OLD.installation_id OR NEW.workspace_id IS NOT OLD.workspace_id
  OR NEW.actor_id IS NOT OLD.actor_id OR NEW.draft_id IS NOT OLD.draft_id
  OR NEW.draft_revision IS NOT OLD.draft_revision OR NEW.connection_id IS NOT OLD.connection_id
  OR NEW.connection_revision IS NOT OLD.connection_revision OR NEW.state_hash IS NOT OLD.state_hash
  OR NEW.origin IS NOT OLD.origin OR NEW.expires_at IS NOT OLD.expires_at OR NEW.created_at IS NOT OLD.created_at
  OR NEW.revision <> OLD.revision + 1
BEGIN SELECT RAISE(ABORT, 'Channel OAuth attempt authority cannot change'); END;
`);
}
