import { ActionButton } from "../../components/ActionButton";
import { FieldHelp } from "../../components/FieldHelp";
import { Panel } from "../../components/Panel";
import { GCCombobox } from "../../components/ui";

export type ChatSessionControlPending =
  | "rename"
  | "organization"
  | "pin"
  | "archive"
  | "delete"
  | "project"
  | "binding"
  | null;

export interface ChatSessionManagementPanelProps {
  renameTitle: string;
  onRenameTitleChange: (value: string) => void;
  folderName: string;
  onFolderNameChange: (value: string) => void;
  tagsValue: string;
  onTagsValueChange: (value: string) => void;
  sending: boolean;
  sessionControlPending: ChatSessionControlPending;
  pinned: boolean;
  archived: boolean;
  selectedSessionProjectValue: string;
  projectOptions: Array<{ value: string; label: string }>;
  onRename: () => void;
  onSaveOrganization: () => void;
  onTogglePin: () => void;
  onToggleArchive: () => void;
  onDelete: () => void;
  onAssignProject: (value: string) => void;
  onExportSnapshot: () => void;
}

export function ChatSessionManagementPanel(props: ChatSessionManagementPanelProps) {
  const {
    renameTitle,
    onRenameTitleChange,
    folderName,
    onFolderNameChange,
    tagsValue,
    onTagsValueChange,
    sending,
    sessionControlPending,
    pinned,
    archived,
    selectedSessionProjectValue,
    projectOptions,
    onRename,
    onSaveOrganization,
    onTogglePin,
    onToggleArchive,
    onDelete,
    onAssignProject,
    onExportSnapshot,
  } = props;

  const disabled = sending || Boolean(sessionControlPending);

  return (
    <Panel
      className="chat-v11-session-bar chat-v11-panel-session"
      title="Session management"
      subtitle="Give this chat a human title, pin it, archive it, delete it, or move it into a project without leaving the thread."
    >
      <FieldHelp>Titles replace autogenerated session keys in the chat rail.</FieldHelp>
      <input
        value={renameTitle}
        onChange={(event) => onRenameTitleChange(event.target.value)}
        placeholder="Give this chat a title"
      />
      <ActionButton label="Save" disabled={disabled} pending={sessionControlPending === "rename"} onClick={onRename} />
      <FieldHelp>
        Folders keep the rail tidy. Tags make quick filters feel lightweight instead of project-heavy.
      </FieldHelp>
      <input
        value={folderName}
        onChange={(event) => onFolderNameChange(event.target.value)}
        placeholder="Folder name (optional)"
      />
      <input
        value={tagsValue}
        onChange={(event) => onTagsValueChange(event.target.value)}
        placeholder="Tags, comma separated"
      />
      <ActionButton
        label="Save organization"
        disabled={disabled}
        pending={sessionControlPending === "organization"}
        onClick={onSaveOrganization}
      />
      <ActionButton
        label={pinned ? "Unpin" : "Pin"}
        disabled={disabled}
        pending={sessionControlPending === "pin"}
        onClick={onTogglePin}
      />
      <ActionButton
        label={archived ? "Restore" : "Archive"}
        disabled={disabled}
        pending={sessionControlPending === "archive"}
        onClick={onToggleArchive}
      />
      <ActionButton
        label="Delete permanently"
        disabled={disabled}
        pending={sessionControlPending === "delete"}
        onClick={onDelete}
      />
      <GCCombobox
        value={selectedSessionProjectValue}
        onChange={onAssignProject}
        placeholder="Pick project"
        disabled={disabled}
        options={projectOptions}
      />
      <ActionButton label="Export snapshot" disabled={disabled} onClick={onExportSnapshot} />
    </Panel>
  );
}
