import { ActionButton } from "../../components/ActionButton";
import { FieldHelp } from "../../components/FieldHelp";
import { Panel } from "../../components/Panel";
import { GCCombobox } from "../../components/ui";

export type ChatSessionControlPending = "rename" | "pin" | "archive" | "delete" | "project" | "binding" | null;

export interface ChatSessionManagementPanelProps {
  renameTitle: string;
  onRenameTitleChange: (value: string) => void;
  sending: boolean;
  sessionControlPending: ChatSessionControlPending;
  pinned: boolean;
  archived: boolean;
  selectedSessionProjectValue: string;
  projectOptions: Array<{ value: string; label: string }>;
  onRename: () => void;
  onTogglePin: () => void;
  onToggleArchive: () => void;
  onDelete: () => void;
  onAssignProject: (value: string) => void;
}

export function ChatSessionManagementPanel(props: ChatSessionManagementPanelProps) {
  const {
    renameTitle,
    onRenameTitleChange,
    sending,
    sessionControlPending,
    pinned,
    archived,
    selectedSessionProjectValue,
    projectOptions,
    onRename,
    onTogglePin,
    onToggleArchive,
    onDelete,
    onAssignProject,
  } = props;

  const disabled = sending || Boolean(sessionControlPending);

  return (
    <Panel
      className="chat-v11-session-bar chat-v11-panel-session"
      title="Session management"
      subtitle="Give this chat a human title, pin it, archive it, delete it, or move it into a project without leaving the thread."
    >
      <FieldHelp>Titles replace autogenerated session keys in the chat rail.</FieldHelp>
      <input
        value={renameTitle}
        onChange={(event) => onRenameTitleChange(event.target.value)}
        placeholder="Give this chat a title"
      />
      <ActionButton label="Save" disabled={disabled} pending={sessionControlPending === "rename"} onClick={onRename} />
      <ActionButton
        label={pinned ? "Unpin" : "Pin"}
        disabled={disabled}
        pending={sessionControlPending === "pin"}
        onClick={onTogglePin}
      />
      <ActionButton
        label={archived ? "Restore" : "Archive"}
        disabled={disabled}
        pending={sessionControlPending === "archive"}
        onClick={onToggleArchive}
      />
      <ActionButton
        label="Delete permanently"
        disabled={disabled}
        pending={sessionControlPending === "delete"}
        onClick={onDelete}
      />
      <GCCombobox
        value={selectedSessionProjectValue}
        onChange={onAssignProject}
        placeholder="Pick project"
        disabled={disabled}
        options={projectOptions}
      />
    </Panel>
  );
}
