import { randomUUID } from "node:crypto";
import type {
  ChatToolRunRecord,
  ChatUserInputPromptRecord,
  ImageGenerationRequest,
  ImageGenerationResponse,
} from "@goatcitadel/contracts";
import { extractPrimaryUserTaskContent } from "../chat-agent-prompt-lab-contract.js";

const SAFE_WRITE_FALLBACK_DIR = "./workspace/goatcitadel_out";
const WRITE_DESTINATION_PROMPT_TITLE = "Choose artifact destination";

interface ArtifactIntentInput {
  content: string;
  sessionId: string;
}

type GenerateImage = (request: ImageGenerationRequest) => Promise<ImageGenerationResponse>;

export function detectPresentationArtifactIntent(content: string): boolean {
  const normalized = content.toLowerCase();
  const presentationPhrase =
    /\b(power\s?point|pptx?|(?:slide|pitch|investor|presentation)\s+deck|slides?|presentation)\b/.test(normalized);
  if (!presentationPhrase) {
    return false;
  }
  return (
    /\b(create|make|build|generate|put|turn|export|save|write|produce|deliver)\b/.test(normalized) ||
    /\b(file|format|artifact|download|power\s?point|pptx?)\b/.test(normalized)
  );
}

export function detectDocumentArtifactIntent(content: string): boolean {
  const normalized = content.toLowerCase();
  const documentPhrase =
    /\b(docx?|word\s+doc(?:ument)?|pdf|markdown|md|html|csv|json|text\s+file|txt|report|brief|memo|handout|worksheet|document)\b/.test(
      normalized,
    );
  if (!documentPhrase) {
    return false;
  }
  return (
    /\b(create|make|build|generate|put|turn|export|save|write|produce|deliver)\b/.test(normalized) ||
    /\b(file|format|artifact|download|docx?|pdf|markdown|html|csv|json)\b/.test(normalized)
  );
}

export function buildSyntheticPresentationCreateArgs(
  input: ArtifactIntentInput,
  safeWriteFallbackDir?: string,
): Record<string, unknown> {
  const task = extractPrimaryUserTaskContent(input.content) ?? input.content;
  const title = inferPresentationTitle(task);
  const path =
    extractAnsweredWriteDestination(input.content) ??
    buildSafeWriteFallbackPath(input.sessionId, "presentations.create", `${title}.pptx`, safeWriteFallbackDir);
  return {
    path: path ?? buildSafeWritePath("presentation.pptx", safeWriteFallbackDir),
    title,
    subtitle: "Generated by GoatCitadel Cowork",
    slides: buildSyntheticPresentationSlides(task, title),
    design: {
      mode: "polished",
      skillId: "design-intelligence",
    },
  };
}

export async function attachGeneratedPresentationVisual(
  args: Record<string, unknown>,
  input: Pick<ArtifactIntentInput, "content">,
  generateImage?: GenerateImage,
): Promise<{ args: Record<string, unknown>; providerCalls: number }> {
  if (!generateImage) {
    return { args, providerCalls: 0 };
  }
  let providerCalls = 0;
  try {
    const prompt = buildPresentationVisualPrompt(input.content, String(args.title ?? "Presentation"), args.slides);
    providerCalls += 1;
    const response = await generateImage({
      providerId: "openai",
      model: "gpt-image-2",
      prompt,
      n: 1,
      outputFormat: "png",
      responseFormat: "b64_json",
      timeoutMs: 45000,
    });
    const image = response.data.find((item) => item.b64Json);
    if (!image?.b64Json) {
      return { args, providerCalls };
    }
    return {
      args: {
        ...args,
        visualAsset: {
          bytesBase64: image.b64Json,
          mimeType: "image/png",
          altText: `Generated supporting visual for ${args.title ?? "presentation"}.`,
          source: response.providerId ?? "openai",
          sourceModel: response.model ?? "gpt-image-2",
          revisedPrompt: image.revisedPrompt,
        },
      },
      providerCalls,
    };
  } catch {
    return { args, providerCalls };
  }
}

function buildPresentationVisualPrompt(content: string, title: string, slidesValue: unknown): string {
  const slideTitles = Array.isArray(slidesValue)
    ? slidesValue
        .map((slide) => (slide && typeof slide === "object" ? (slide as { title?: unknown }).title : undefined))
        .filter((item): item is string => typeof item === "string" && item.trim().length > 0)
        .slice(0, 5)
        .join("; ")
    : "";
  return [
    `Create a polished PowerPoint-supporting visual for "${title}".`,
    "Use a clean editorial cover composition with strong hierarchy, generous negative space, and no readable text.",
    "The image should work as a title-slide anchor; the renderer will create distinct supporting visuals per slide.",
    slideTitles ? `Deck sections: ${slideTitles}.` : undefined,
    `User request: ${content.replace(/\s+/g, " ").trim().slice(0, 600)}`,
  ]
    .filter(Boolean)
    .join(" ");
}

export function buildSyntheticDocumentCreateArgs(
  input: ArtifactIntentInput,
  safeWriteFallbackDir?: string,
): Record<string, unknown> {
  const task = extractPrimaryUserTaskContent(input.content) ?? input.content;
  const title = inferDocumentTitle(task);
  const format = inferDocumentFormat(task);
  const path =
    extractAnsweredWriteDestination(input.content) ??
    buildSafeWriteFallbackPath(
      input.sessionId,
      "documents.create",
      `${title}.${documentFormatExtension(format)}`,
      safeWriteFallbackDir,
    );
  return {
    path: path ?? buildSafeWritePath(`document.${documentFormatExtension(format)}`, safeWriteFallbackDir),
    format,
    title,
    body: `Generated document for: ${task.trim().replace(/\s+/g, " ").slice(0, 500)}`,
    sections: buildSyntheticDocumentSections(task),
    design: inferDocumentDesignRequest(format),
  };
}

function inferPresentationTitle(content: string): string {
  const normalized = content.replace(/\s+/g, " ").trim();
  const quotedTitle = normalized.match(/["'`](.{8,90}?)["'`]/)?.[1]?.trim();
  if (quotedTitle) {
    return titleCasePresentationText(quotedTitle);
  }
  if (/\bfree time\b/i.test(normalized) && /\btop\s*10\b/i.test(normalized)) {
    return "Top 10 Things To Do In Free Time";
  }
  const topic =
    normalized.match(/\b(?:about|on|for)\s+(.{8,100}?)(?:\.|$|\n)/i)?.[1]?.trim() ??
    normalized
      .match(/\b(?:power\s?point|pptx?|presentation|slides?|deck)\b\s+(?:about|on|for)?\s*(.{8,100}?)(?:\.|$|\n)/i)?.[1]
      ?.trim();
  return titleCasePresentationText(topic ?? "Presentation");
}

function inferDocumentTitle(content: string): string {
  const normalized = content.replace(/\s+/g, " ").trim();
  const quotedTitle = normalized.match(/["'`](.{8,90}?)["'`]/)?.[1]?.trim();
  if (quotedTitle) {
    return titleCasePresentationText(quotedTitle);
  }
  if (/\bfree time\b/i.test(normalized) && /\btop\s*10\b/i.test(normalized)) {
    return "Top 10 Things To Do In Free Time";
  }
  const topic =
    normalized.match(/\b(?:about|on|for)\s+(.{8,100}?)(?:\.|$|\n)/i)?.[1]?.trim() ??
    normalized
      .match(
        /\b(?:docx?|document|report|brief|memo|handout|worksheet|pdf|markdown|html|csv|json)\b\s+(?:about|on|for)?\s*(.{8,100}?)(?:\.|$|\n)/i,
      )?.[1]
      ?.trim();
  return titleCasePresentationText(topic ?? "Document");
}

function inferDocumentFormat(content: string): string {
  const normalized = content.toLowerCase();
  if (/\bpdf\b/.test(normalized)) {
    return "pdf";
  }
  if (/\b(docx?|word\s+doc(?:ument)?)\b/.test(normalized)) {
    return "docx";
  }
  if (/\bhtml?\b/.test(normalized)) {
    return "html";
  }
  if (/\bcsv\b/.test(normalized)) {
    return "csv";
  }
  if (/\bjson\b/.test(normalized)) {
    return "json";
  }
  if (/\b(?:txt|text\s+file)\b/.test(normalized)) {
    return "txt";
  }
  if (/\b(?:md|markdown)\b/.test(normalized)) {
    return "markdown";
  }
  return "docx";
}

function documentFormatExtension(format: string): string {
  return format === "markdown" ? "md" : format;
}

function inferDocumentDesignRequest(format: string): Record<string, unknown> {
  if (/^(?:json|csv|txt|text)$/iu.test(format)) {
    return {
      mode: "minimal",
    };
  }
  return {
    mode: "polished",
    skillId: "design-intelligence",
  };
}

function titleCasePresentationText(value: string): string {
  const cleaned = value
    .replace(
      /\b(?:please|create|make|build|generate|put|together|presentation|power\s?point|pptx?|slides?|deck|artifact|file)\b/gi,
      " ",
    )
    .replace(/[^a-zA-Z0-9\s'-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 90);
  if (!cleaned) {
    return "Presentation";
  }
  return cleaned
    .split(" ")
    .map((word) =>
      /^(?:a|an|and|as|at|but|by|for|in|near|of|on|or|the|to|with)$/i.test(word)
        ? word.toLowerCase()
        : `${word.slice(0, 1).toUpperCase()}${word.slice(1).toLowerCase()}`,
    )
    .join(" ")
    .replace(/\b(?:Ai|Api|Ui|Ux|Pptx)\b/g, (match) => match.toUpperCase());
}

function buildSyntheticPresentationSlides(content: string, title: string): Array<{ title: string; bullets: string[] }> {
  const bullets = extractPresentationBulletsFromPrompt(content);
  return [
    {
      title,
      bullets: [
        "Summarizes the requested topic in a shareable slide format",
        "Keeps the deck concise and easy to edit",
        "Uses a real PPTX artifact rather than text-only presentation notes",
      ],
    },
    {
      title: "Key Points",
      bullets,
    },
    {
      title: "Recommended Structure",
      bullets: ["Open with the purpose", "Group details into clear sections", "Close with next steps or takeaways"],
    },
  ];
}

function buildSyntheticDocumentSections(content: string): Array<{ heading: string; body: string; bullets: string[] }> {
  const bullets = extractPresentationBulletsFromPrompt(content);
  if (/\bfree time\b/i.test(content)) {
    return [
      {
        heading: "Recommended Activities",
        body: "A balanced free-time plan mixes active, creative, social, and restorative options.",
        bullets: [
          "Read or learn something new",
          "Walk, exercise, or explore locally",
          "Cook, create, volunteer, connect, and rest",
        ],
      },
      {
        heading: "How To Choose",
        body: "Pick activities based on available time, energy level, budget, and whether you want solitude or company.",
        bullets: [
          "Keep low-friction options ready",
          "Rotate familiar favorites with new experiments",
          "Notice what leaves you better afterward",
        ],
      },
    ];
  }
  return [
    {
      heading: "Summary",
      body: "This document turns the requested response into a real file artifact.",
      bullets,
    },
    {
      heading: "Next Steps",
      body: "Review the generated file, then refine sections, formatting, or audience-specific details as needed.",
      bullets: [
        "Confirm the intended audience",
        "Adjust wording and emphasis",
        "Add source citations when the task used research",
      ],
    },
  ];
}

function extractPresentationBulletsFromPrompt(content: string): string[] {
  const lines = content
    .split(/\r?\n|[.;]/)
    .map((line) => line.replace(/^[-*\d.)\s]+/, "").trim())
    .filter((line) => line.length >= 12 && !/^suggested tools:/i.test(line))
    .slice(0, 5);
  return lines.length > 0
    ? lines.map((line) => line.slice(0, 180))
    : ["Clarify the main audience", "Focus each slide on one idea", "Keep bullets brief and scannable"];
}

export function mergePresentationArtifactDeliveryContent(existingContent: string, toolRun: ChatToolRunRecord): string {
  if (toolRun.status !== "executed") {
    const failure = toolRun.error ?? "the presentation tool did not complete";
    const fallback = `I tried to create the PowerPoint artifact with \`presentations.create\`, but ${failure}.`;
    return existingContent.trim().length > 0 ? `${existingContent.trim()}\n\n${fallback}` : fallback;
  }
  const result = (toolRun.result ?? {}) as Record<string, unknown>;
  const path =
    typeof result.path === "string"
      ? result.path
      : typeof result.fallbackPath === "string"
        ? result.fallbackPath
        : typeof toolRun.args?.path === "string"
          ? toolRun.args.path
          : "the requested PPTX path";
  const slideCount = typeof result.slideCount === "number" ? result.slideCount : undefined;
  const bytesWritten = typeof result.bytesWritten === "number" ? result.bytesWritten : undefined;
  const delivery = [
    `Created the PowerPoint presentation artifact at \`${path}\`.`,
    slideCount !== undefined ? `Slides: ${slideCount}.` : undefined,
    bytesWritten !== undefined ? `Size: ${bytesWritten} bytes.` : undefined,
  ]
    .filter(Boolean)
    .join(" ");
  const trimmed = existingContent.trim();
  if (!trimmed || looksLikeMissingPresentationArtifactContent(trimmed)) {
    return delivery;
  }
  if (trimmed.includes(path)) {
    return trimmed;
  }
  return `${trimmed}\n\n${delivery}`;
}

function looksLikeMissingPresentationArtifactContent(content: string): boolean {
  return (
    /\b(?:could not|couldn't|unable to|did not|didn't|not able to|no verified|not created|was not created)\b/i.test(
      content,
    ) && /\b(?:pptx?|power\s?point|presentation|slides?|deck|artifact|file)\b/i.test(content)
  );
}

export function mergeDocumentArtifactDeliveryContent(existingContent: string, toolRun: ChatToolRunRecord): string {
  if (toolRun.status !== "executed") {
    const failure = toolRun.error ?? "the document tool did not complete";
    const fallback = `I tried to create the document artifact with \`documents.create\`, but ${failure}.`;
    return existingContent.trim().length > 0 ? `${existingContent.trim()}\n\n${fallback}` : fallback;
  }
  const result = (toolRun.result ?? {}) as Record<string, unknown>;
  const path =
    typeof result.path === "string"
      ? result.path
      : typeof result.fallbackPath === "string"
        ? result.fallbackPath
        : typeof toolRun.args?.path === "string"
          ? toolRun.args.path
          : "the requested document path";
  const format = typeof result.format === "string" ? result.format.toUpperCase() : undefined;
  const bytesWritten = typeof result.bytesWritten === "number" ? result.bytesWritten : undefined;
  const delivery = [
    `Created the document artifact at \`${path}\`.`,
    format ? `Format: ${format}.` : undefined,
    bytesWritten !== undefined ? `Size: ${bytesWritten} bytes.` : undefined,
  ]
    .filter(Boolean)
    .join(" ");
  const trimmed = existingContent.trim();
  if (!trimmed || looksLikeMissingDocumentArtifactContent(trimmed)) {
    return delivery;
  }
  if (trimmed.includes(path)) {
    return trimmed;
  }
  return `${trimmed}\n\n${delivery}`;
}

function looksLikeMissingDocumentArtifactContent(content: string): boolean {
  return (
    /\b(?:could not|couldn't|unable to|did not|didn't|not able to|no verified|not created|was not created)\b/i.test(
      content,
    ) &&
    /\b(?:docx?|word\s+doc(?:ument)?|pdf|markdown|md|html|csv|json|txt|report|brief|memo|document|artifact|file)\b/i.test(
      content,
    )
  );
}

export function isWriteJailBlockReason(reason: string | undefined): boolean {
  if (!reason) {
    return false;
  }
  const normalized = reason.toLowerCase();
  return normalized.includes("write jail") || normalized.includes("outside write");
}

export function isWriteDestinationTool(toolName: string): boolean {
  return (
    toolName === "fs.write" ||
    toolName === "artifacts.create" ||
    toolName === "documents.create" ||
    toolName === "presentations.create"
  );
}

export function buildWriteDestinationUserInputPrompt(input: {
  sessionId: string;
  turnId: string;
  toolName: string;
  requestedPath: unknown;
  policyReason?: string;
  fallbackPath?: string;
  safeWriteFallbackDir?: string;
}): ChatUserInputPromptRecord | undefined {
  if (!isWriteDestinationTool(input.toolName) || !isWriteJailBlockReason(input.policyReason)) {
    return undefined;
  }
  const requestedPath = typeof input.requestedPath === "string" ? input.requestedPath.trim() : "";
  const suggestedPath =
    input.fallbackPath ??
    buildSafeWriteFallbackPath(input.sessionId, input.toolName, requestedPath, input.safeWriteFallbackDir);
  const blockedTarget = requestedPath ? ` Requested path: ${requestedPath}.` : "";
  const suggestion = suggestedPath
    ? ` Enter a destination inside an allowed write root, for example ${suggestedPath}.`
    : " Enter a destination inside one of the configured write-jail roots.";
  return {
    promptId: `write-destination-${randomUUID()}`,
    turnId: input.turnId,
    kind: "text",
    title: WRITE_DESTINATION_PROMPT_TITLE,
    question: `I could not create this file because the path is outside the configured write jail.${blockedTarget}${suggestion}`,
    required: true,
    placeholder: suggestedPath ?? "workspace/goatcitadel_out/output.txt",
    submitLabel: "Create file",
  };
}

export function buildSafeWritePath(fileName: string, safeWriteFallbackDir?: string): string {
  const directory = (safeWriteFallbackDir?.trim() || SAFE_WRITE_FALLBACK_DIR).replace(/[\\/]+$/u, "");
  return `${directory}/${fileName}`;
}

export function buildSafeWriteFallbackPath(
  sessionId: string,
  toolName: string,
  originalPath: unknown,
  safeWriteFallbackDir?: string,
): string | undefined {
  const safeSessionId = sessionId
    .trim()
    .replace(/[^a-zA-Z0-9_-]+/g, "-")
    .slice(-32);
  if (!safeSessionId) {
    return undefined;
  }
  const original = typeof originalPath === "string" ? originalPath.trim() : "";
  const normalizedOriginal = original.replaceAll("\\", "/");
  const fileName = normalizedOriginal.split("/").pop() ?? "";
  const match = fileName.match(/^(.+?)(\.[a-zA-Z0-9_-]{1,12})$/);
  const baseName = (match?.[1] ?? fileName).trim();
  const ext = (match?.[2] ?? "").trim();
  const safeBaseName =
    sanitizePathSegment(baseName) ||
    (toolName === "presentations.create"
      ? "presentation"
      : toolName === "documents.create"
        ? "document"
        : toolName === "artifacts.create"
          ? "artifact"
          : "output");
  const fallbackExt =
    ext ||
    (toolName === "presentations.create"
      ? ".pptx"
      : toolName === "documents.create"
        ? ".docx"
        : toolName === "artifacts.create"
          ? ".md"
          : ".txt");
  return buildSafeWritePath(`${safeBaseName}-${safeSessionId}${fallbackExt}`, safeWriteFallbackDir);
}

export function extractAnsweredWriteDestination(content: string): string | undefined {
  const match = content.match(
    /(?:choose artifact destination|where should i create|destination inside an allowed write root)[\s\S]{0,900}?Answer:\s*([^\r\n]+)/i,
  );
  const answer = match?.[1]?.trim();
  if (!answer || /^(?:none|skip|cancel)$/i.test(answer)) {
    return undefined;
  }
  return answer.replace(/^`|`$/g, "").trim();
}

function sanitizePathSegment(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}

export function normalizePathForComparison(value: string): string {
  return value.replaceAll("\\", "/").toLowerCase();
}
