import { describe, expect, it, vi } from "vitest";
import { ChannelSecretCustodyService } from "./channel-secret-custody-service.js";
import type { ChannelSetupDraft } from "@goatcitadel/contracts";
import type { ChannelSetupHost } from "./channel-setup-service.js";
import { discoverChannelSetupTelegramTargets } from "./channel-setup-telegram-discovery.js";
const revision = "a".repeat(64);
function host(webhook = true): ChannelSetupHost { const connection = { connectionId: "connection", revision, catalogId: "channel.telegram", key: "telegram", kind: "channel", config: { botToken: "keychain:opaque", targets: [{ chatId: "123", label: "Home", default: true }] } }; return { storage: {}, getIntegrationConnection: vi.fn(async () => connection), resolveConnectionSecret: vi.fn(() => "test-token"), isConnectionUrlAllowlisted: () => true, fetchWithTimeout: vi.fn(async (url: string) => new Response(JSON.stringify({ ok: true, result: url.endsWith("getMe") ? { id: 42, username: "bot" } : url.endsWith("getWebhookInfo") ? { url: webhook ? "https://gateway.example/webhook" : "" } : [] }), { status: 200 })) } as unknown as ChannelSetupHost; }
describe("credential-safe Telegram discovery", () => {
  it("preserves active webhooks and shows configured destinations without getUpdates", async () => { const h = host(); const response = await discoverChannelSetupTelegramTargets(h, { source: "connection", connectionId: "connection", expectedConnectionRevision: revision }); expect(response).toMatchObject({ webhookActive: true, botIdentity: { id: "42" }, items: [{ chatId: "123", source: "connection_config" }] }); expect(h.fetchWithTimeout).toHaveBeenCalledTimes(2); expect(JSON.stringify(response)).not.toContain("keychain"); expect(JSON.stringify(response)).not.toContain("test-token"); });
  it("discovers from a revision-bound new draft using secure custody without re-entering credentials", async () => { const h = host(); const values = new Map<string, string>(); const custody = new ChannelSecretCustodyService({ setSecret: (account: string, value: string) => void values.set(account, value), getSecret: (account: string) => values.get(account), deleteSecret: (account: string) => void values.delete(account) } as never); const draftId = "11111111-1111-1111-1111-111111111111"; const secretRef = custody.storeTemporary(draftId, "botToken", "test-token"); const draft = { draftId, revision: 3, catalogId: "channel.telegram", lifecycleMode: "create", draft: { defaultChatId: "123", inboundAccessMode: "allowlist" }, secretState: { botToken: { configured: true, custody: "temporary", secretRef } }, enabled: true, contentVersion: "content", testVersion: "test", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() } as ChannelSetupDraft; h.storage.channelSetupDrafts = { get: vi.fn(async () => draft) } as never; h.channelSecrets = custody; const response = await discoverChannelSetupTelegramTargets(h, { source: "draft", draftId, expectedRevision: 3 }); expect(response.botIdentity?.id).toBe("42"); expect(h.resolveConnectionSecret).toHaveBeenCalledWith(expect.objectContaining({ botToken: "test-token" }), "botToken", "botTokenEnv", "channel.telegram"); expect(h.getIntegrationConnection).not.toHaveBeenCalled(); expect(JSON.stringify(response)).not.toContain(secretRef); await expect(discoverChannelSetupTelegramTargets(h, { source: "draft", draftId, expectedRevision: 2 })).rejects.toThrow("changed"); });
  it("fails a stale connection before making an external request", async () => { const h = host(); await expect(discoverChannelSetupTelegramTargets(h, { source: "connection", connectionId: "connection", expectedConnectionRevision: "b".repeat(64) })).rejects.toThrow("changed"); expect(h.fetchWithTimeout).not.toHaveBeenCalled(); });
  it("fails a foreign-channel credential before making an external request", async () => { const h = host(); h.getIntegrationConnection = vi.fn(async () => ({ key: "slack", kind: "channel" }) as never); await expect(discoverChannelSetupTelegramTargets(h, { source: "connection", connectionId: "connection", expectedConnectionRevision: revision })).rejects.toThrow("Telegram"); });
  it("never exposes a credential-bearing transport error", async () => { const h = host(); h.fetchWithTimeout = vi.fn(async () => { throw new Error("Network failed https://api.telegram.org/bottest-token/getMe keychain:opaque"); }); await expect(discoverChannelSetupTelegramTargets(h, { source: "connection", connectionId: "connection", expectedConnectionRevision: revision })).rejects.toThrow("could not complete"); try { await discoverChannelSetupTelegramTargets(h, { source: "connection", connectionId: "connection", expectedConnectionRevision: revision }); } catch (error) { expect(String(error)).not.toContain("test-token"); expect(String(error)).not.toContain("keychain"); } });
  it("does not treat an identity conflict as authenticated discovery", async () => { const h = host(); h.fetchWithTimeout = vi.fn(async () => new Response(JSON.stringify({ ok: false }), { status: 409 })); await expect(discoverChannelSetupTelegramTargets(h, { source: "connection", connectionId: "connection", expectedConnectionRevision: revision })).rejects.toThrow("could not complete"); expect(h.fetchWithTimeout).toHaveBeenCalledOnce(); });
});
