import { randomUUID } from "node:crypto";
import { describe, expect, it, vi } from "vitest";
import type { ChannelSetupDraft, ChannelSetupEvidence, ChannelSetupTestResult } from "@goatcitadel/contracts";
import { finalizeChannelSetupDraft } from "./channel-setup-service.js";
import type { ChannelSetupHost } from "./channel-setup-service.js";
import { acknowledgeChannelSetupTest, persistChannelSetupTestEvidence, restoreChannelSetupTestEvidence } from "./channel-setup-evidence-service.js";
import { buildEphemeralChannelConnection } from "./channel-setup-helpers.js";
import { buildChannelSetupRecentTestSignature } from "./channel-setup-test-cache.js";
import { evaluateChannelSetupEligibility } from "./channel-setup-eligibility.js";
import { requireChannelSetupDefinition } from "./channel-setup-definitions.js";
function fixture() {
  const definition = requireChannelSetupDefinition("channel.telegram").definition;
  const draft: ChannelSetupDraft = { draftId: randomUUID(), revision: 3, catalogId: "channel.telegram", lifecycleMode: "create", enabled: true, draft: { botTokenEnv: "TELEGRAM_BOT_TOKEN", defaultChatId: "123", inboundAccessMode: "allowlist" }, secretState: {}, contentVersion: definition.wizard.contentVersion, adapterVersion: definition.adapter.adapterVersion, validationVersion: definition.validation.validationVersion, testVersion: definition.testing.testVersion, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() };
  const records: ChannelSetupEvidence[] = [];
  const host = { recentChannelSetupTests: new Map(), storage: { channelSetupDrafts: { get: async () => draft }, channelSetupEvidence: { create: async (input: ChannelSetupEvidence) => { const record = { ...input, evidenceId: input.evidenceId ?? randomUUID(), createdAt: new Date().toISOString() }; records.unshift(record); return record; }, get: async (id: string) => records.find((record) => record.evidenceId === id), list: async () => records } } } as unknown as ChannelSetupHost;
  return { draft, host, records };
}
describe("immutable setup evidence recovery", () => {
  it("restores unchanged fresh proof after cache loss and rejects changed inputs", async () => { const { draft, host } = fixture(); const connection = await buildEphemeralChannelConnection(host, draft); const result: ChannelSetupTestResult = { draftId: draft.draftId, draftRevision: draft.revision, status: "ok", issues: [], levels: [], checkedAt: new Date().toISOString() }; await persistChannelSetupTestEvidence(host, draft, result, buildChannelSetupRecentTestSignature(draft, connection, draft.testVersion)); expect((await restoreChannelSetupTestEvidence(host, draft, connection))?.finalizationEligibility?.allowed).toBe(true); draft.draft.defaultChatId = "456"; expect(await restoreChannelSetupTestEvidence(host, draft, await buildEphemeralChannelConnection(host, draft))).toBeUndefined(); });
  it("records cleanup acknowledgement without advancing the draft or extending freshness", async () => { const { draft, host, records } = fixture(); const connection = await buildEphemeralChannelConnection(host, draft); const result: ChannelSetupTestResult = { draftId: draft.draftId, draftRevision: draft.revision, status: "warn", issues: [{ key: "telegram_sandbox_cleanup", level: "warn", message: "Manual cleanup needed" }], levels: [], checkedAt: new Date().toISOString(), probe: { kind: "telegram", checkedAt: new Date().toISOString(), steps: [{ key: "telegram_sandbox_send", label: "Send", status: "pass", message: "Accepted", providerMessageId: "receipt" }, { key: "telegram_sandbox_cleanup", label: "Cleanup", status: "warn", message: "Manual cleanup needed", disposition: "advisory" }] } }; result.finalizationEligibility = evaluateChannelSetupEligibility(result, connection); const test = await persistChannelSetupTestEvidence(host, draft, result, buildChannelSetupRecentTestSignature(draft, connection, draft.testVersion)); const ack = await acknowledgeChannelSetupTest(host, draft.draftId, { expectedRevision: 3, evidenceId: test.evidenceId!, acknowledgement: "cleanup" }, "operator"); expect(ack.draftRevision).toBe(3); expect(ack.checkedAt).toBe(test.checkedAt); expect(ack.status).toBe("warn"); expect(ack.finalizationEligibility?.allowed).toBe(true); expect(records[0]).toMatchObject({ phase: "acknowledgement", priorEvidenceId: test.evidenceId, actorId: "operator", draftRevision: 3 }); const receipt = await acknowledgeChannelSetupTest(host, draft.draftId, { expectedRevision: 3, evidenceId: ack.evidenceId!, acknowledgement: "receipt" }, "operator"); host.recentChannelSetupTests.clear(); expect((await restoreChannelSetupTestEvidence(host, draft, connection))?.evidenceId).toBe(receipt.evidenceId); expect((await restoreChannelSetupTestEvidence(host, draft, connection))?.finalizationEligibility?.allowed).toBe(true); });
  it("keeps the latest same-input failure blocked after restart instead of reviving older success", async () => { const { draft, host } = fixture(); const connection = await buildEphemeralChannelConnection(host, draft); const fingerprint = buildChannelSetupRecentTestSignature(draft, connection, draft.testVersion); await persistChannelSetupTestEvidence(host, draft, { draftId: draft.draftId, draftRevision: 3, status: "ok", levels: [], issues: [], checkedAt: new Date().toISOString() }, fingerprint); const failed = await persistChannelSetupTestEvidence(host, draft, { draftId: draft.draftId, draftRevision: 3, status: "error", levels: [], issues: [{ key: "telegram_auth", level: "error", message: "Credential rejected" }], checkedAt: new Date().toISOString() }, fingerprint); const restored = await restoreChannelSetupTestEvidence(host, draft, connection); expect(restored?.evidenceId).toBe(failed.evidenceId); expect(restored?.status).toBe("error"); expect(restored?.finalizationEligibility?.allowed).toBe(false); });
  it("does not acknowledge an older successful receipt after a newer failed test", async () => { const { draft, host } = fixture(); const connection = await buildEphemeralChannelConnection(host, draft); const fingerprint = buildChannelSetupRecentTestSignature(draft, connection, draft.testVersion); const success = await persistChannelSetupTestEvidence(host, draft, { draftId: draft.draftId, draftRevision: 3, status: "ok", levels: [], issues: [], checkedAt: new Date().toISOString(), probe: { kind: "telegram", checkedAt: new Date().toISOString(), steps: [{ key: "telegram_sandbox_send", label: "Send", status: "pass", message: "Accepted", providerMessageId: "receipt" }] } }, fingerprint); await persistChannelSetupTestEvidence(host, draft, { draftId: draft.draftId, draftRevision: 3, status: "error", levels: [], issues: [{ key: "telegram_auth", level: "error", message: "Credential rejected" }], checkedAt: new Date().toISOString() }, fingerprint); await expect(acknowledgeChannelSetupTest(host, draft.draftId, { expectedRevision: 3, evidenceId: success.evidenceId!, acknowledgement: "receipt" }, "operator")).rejects.toThrow("latest result"); });
  it("rejects a delayed cached acknowledgement when a newer canonical test failed", async () => {
    const { draft, host } = fixture();
    const connection = await buildEphemeralChannelConnection(host, draft);
    const fingerprint = buildChannelSetupRecentTestSignature(draft, connection, draft.testVersion);
    const success = await persistChannelSetupTestEvidence(host, draft, { draftId: draft.draftId, draftRevision: 3, status: "ok", levels: [], issues: [], checkedAt: new Date().toISOString(), probe: { kind: "telegram", checkedAt: new Date().toISOString(), steps: [{ key: "telegram_sandbox_send", label: "Send", status: "pass", message: "Accepted", providerMessageId: "receipt" }] } }, fingerprint);
    const olderAck = await acknowledgeChannelSetupTest(host, draft.draftId, { expectedRevision: 3, evidenceId: success.evidenceId!, acknowledgement: "receipt" }, "operator");
    await persistChannelSetupTestEvidence(host, draft, { draftId: draft.draftId, draftRevision: 3, status: "error", levels: [], issues: [{ key: "telegram_auth", level: "error", message: "Credential rejected" }], checkedAt: new Date().toISOString() }, fingerprint);
    // Model the older acknowledgement resolving after the newer test deleted its cache.
    host.recentChannelSetupTests.set(draft.draftId, { signature: fingerprint, result: olderAck });
    host.storage.channelSetupDrafts.update = vi.fn(async (_id, input) => {
      if (input.expectedRevision !== draft.revision) throw new Error("stale revision");
      Object.assign(draft, { ...input, revision: draft.revision + 1 });
      return draft;
    });
    host.recordDevDiagnostic = vi.fn();
    host.commitChannelSetupConnection = vi.fn();
    host.runIntegrationConnectionLiveChecks = vi.fn();
    await expect(finalizeChannelSetupDraft(host, draft.draftId, 3)).rejects.toThrow("Required setup checks failed");
    expect(host.commitChannelSetupConnection).not.toHaveBeenCalled();
    expect(host.runIntegrationConnectionLiveChecks).not.toHaveBeenCalled();
  });
  it("rejects acknowledgement of expired or foreign proof", async () => { const { draft, host } = fixture(); const connection = await buildEphemeralChannelConnection(host, draft); const source = await persistChannelSetupTestEvidence(host, draft, { draftId: draft.draftId, draftRevision: 3, status: "ok", levels: [], issues: [], checkedAt: new Date(Date.now() - 360000).toISOString() }, buildChannelSetupRecentTestSignature(draft, connection, draft.testVersion)); await expect(acknowledgeChannelSetupTest(host, draft.draftId, { expectedRevision: 3, evidenceId: source.evidenceId!, acknowledgement: "receipt" }, "operator")).rejects.toThrow("freshness"); await expect(acknowledgeChannelSetupTest(host, draft.draftId, { expectedRevision: 3, evidenceId: randomUUID(), acknowledgement: "receipt" }, "operator")).rejects.toThrow("belonging"); });
});
