import type { McpServerTemplateRecord } from "@goatcitadel/contracts";
import { MCP_APPROVAL_DELIVERY_TOOL_NAME, MCP_APPROVAL_INBOX_URL } from "./mcp-approval-inbox.js";
import { MCP_DURABLE_TASKS_URL } from "./mcp-durable-tasks.js";

export const MCP_SERVER_TEMPLATES: McpServerTemplateRecord[] = [
  {
    templateId: "approval-inbox",
    label: "GoatCitadel Approval Inbox",
    description:
      "Internal MCP receiver for durable approval deliveries, inbox review, and non-browser approval resolution.",
    transport: "http",
    url: MCP_APPROVAL_INBOX_URL,
    authType: "none",
    category: "orchestration",
    trustTier: "trusted",
    costTier: "free",
    policy: {
      requireFirstToolApproval: false,
      redactionMode: "basic",
      allowedToolPatterns: [MCP_APPROVAL_DELIVERY_TOOL_NAME, "goatcitadel.approval.remote_action_inbox.*"],
      blockedToolPatterns: [],
    },
    enabledByDefault: false,
  },
  {
    templateId: "durable-tasks",
    label: "GoatCitadel Durable Tasks",
    description:
      "Internal MCP surface exposing durable agent tasks (long-running async runs) for list/get/cancel (MCP v2 Tasks).",
    transport: "http",
    url: MCP_DURABLE_TASKS_URL,
    authType: "none",
    category: "orchestration",
    trustTier: "trusted",
    costTier: "free",
    policy: {
      requireFirstToolApproval: false,
      redactionMode: "basic",
      allowedToolPatterns: ["goatcitadel.durable.tasks.*"],
      blockedToolPatterns: [],
    },
    enabledByDefault: false,
  },
  {
    templateId: "filesystem",
    label: "Filesystem (Local)",
    description: "Read and write local workspace files through MCP.",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-filesystem", "."],
    authType: "none",
    category: "development",
    trustTier: "restricted",
    costTier: "free",
    policy: {
      requireFirstToolApproval: true,
      redactionMode: "basic",
      allowedToolPatterns: [],
      blockedToolPatterns: [],
    },
    enabledByDefault: false,
  },
  {
    templateId: "fetch",
    label: "Fetch (HTTP)",
    description: "Web fetch/search helper MCP server for research tasks.",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-fetch"],
    authType: "none",
    category: "research",
    trustTier: "restricted",
    costTier: "free",
    policy: {
      requireFirstToolApproval: true,
      redactionMode: "basic",
      allowedToolPatterns: [],
      blockedToolPatterns: [],
    },
    enabledByDefault: false,
  },
  {
    templateId: "playwright",
    label: "Playwright Browser",
    description: "Browser automation MCP server for dynamic website workflows.",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-playwright"],
    authType: "none",
    category: "automation",
    trustTier: "restricted",
    costTier: "free",
    policy: {
      requireFirstToolApproval: true,
      redactionMode: "basic",
      allowedToolPatterns: [],
      blockedToolPatterns: [],
    },
    enabledByDefault: false,
  },
  {
    templateId: "github",
    label: "GitHub",
    description: "Official GitHub MCP endpoint for repositories, pull requests, issues, and code navigation.",
    transport: "http",
    url: "https://api.githubcopilot.com/mcp/",
    authType: "oauth2",
    category: "development",
    trustTier: "restricted",
    costTier: "mixed",
    policy: {
      requireFirstToolApproval: true,
      redactionMode: "strict",
      allowedToolPatterns: [],
      blockedToolPatterns: [],
    },
    enabledByDefault: false,
  },
  {
    templateId: "stripe",
    label: "Stripe",
    description:
      "Official Stripe remote MCP server for customers, subscriptions, invoices, and billing support workflows.",
    transport: "http",
    url: "https://mcp.stripe.com",
    authType: "oauth2",
    category: "automation",
    trustTier: "restricted",
    costTier: "mixed",
    policy: {
      requireFirstToolApproval: true,
      redactionMode: "strict",
      allowedToolPatterns: [],
      blockedToolPatterns: [],
    },
    enabledByDefault: false,
  },
  {
    templateId: "context7",
    label: "Context7",
    description: "Up-to-date library and framework documentation search via the official Context7 MCP server.",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@upstash/context7-mcp@latest"],
    authType: "none",
    category: "research",
    trustTier: "restricted",
    costTier: "free",
    policy: {
      requireFirstToolApproval: true,
      redactionMode: "basic",
      allowedToolPatterns: [],
      blockedToolPatterns: [],
    },
    enabledByDefault: false,
  },
  {
    templateId: "microsoft-learn",
    label: "Microsoft Learn",
    description:
      "Official Microsoft Learn MCP endpoint for current Microsoft documentation, examples, and how-to guidance.",
    transport: "http",
    url: "https://learn.microsoft.com/api/mcp",
    authType: "none",
    category: "research",
    trustTier: "trusted",
    costTier: "free",
    policy: {
      requireFirstToolApproval: true,
      redactionMode: "basic",
      allowedToolPatterns: [],
      blockedToolPatterns: [],
    },
    enabledByDefault: false,
  },
  {
    templateId: "n8n",
    label: "n8n",
    description: "Connect GoatCitadel to an n8n MCP endpoint for workflow execution and automation handoff.",
    transport: "sse",
    url: "https://your-n8n-host/mcp/<server-id>/sse",
    authType: "token",
    category: "automation",
    trustTier: "restricted",
    costTier: "mixed",
    policy: {
      requireFirstToolApproval: true,
      redactionMode: "strict",
      allowedToolPatterns: [],
      blockedToolPatterns: [],
    },
    enabledByDefault: false,
  },
  {
    templateId: "gpt-researcher",
    label: "GPT Researcher",
    description: "Structured deep-research MCP server for investigation workflows and source-grounded reports.",
    transport: "stdio",
    command: "uvx",
    args: ["gpt-researcher-mcp"],
    authType: "none",
    category: "research",
    trustTier: "restricted",
    costTier: "mixed",
    policy: {
      requireFirstToolApproval: true,
      redactionMode: "basic",
      allowedToolPatterns: [],
      blockedToolPatterns: [],
    },
    enabledByDefault: false,
  },
  {
    templateId: "openspec",
    label: "OpenSpec",
    description: "MCP bridge for OpenSpec-style spec and analysis workflows.",
    transport: "stdio",
    command: "uvx",
    args: ["openspec-mcp"],
    authType: "none",
    category: "development",
    trustTier: "restricted",
    costTier: "free",
    policy: {
      requireFirstToolApproval: true,
      redactionMode: "basic",
      allowedToolPatterns: [],
      blockedToolPatterns: [],
    },
    enabledByDefault: false,
  },
];
