import type { RuntimeSettingsResponse } from "@goatcitadel/mission-control-shared/api/client";

export function gatewayAuthSettingsFixture(): RuntimeSettingsResponse {
  return {
    revision: 41,
    environment: "test",
    deploymentProfile: "local_dev",
    toolApprovalMode: "approve_all",
    budgetMode: "balanced",
    workspaceDir: "./test-workspace",
    writeJailRoots: [],
    readOnlyRoots: [],
    networkAllowlist: [],
    approvalExplainer: {
      enabled: false,
      mode: "async",
      minRiskLevel: "caution",
      timeoutMs: 1000,
      maxPayloadChars: 1000,
    },
    memory: {
      enabled: false,
      qmd: {
        enabled: false,
        applyToChat: false,
        applyToOrchestration: false,
        minPromptChars: 100,
        maxContextTokens: 1000,
        cacheTtlSeconds: 60,
      },
    },
    auth: {
      mode: "token",
      allowLoopbackBypass: false,
      tokenConfigured: true,
      basicConfigured: false,
      plan: {
        mode: "token",
        warnings: [],
        token: { configured: true, source: "runtime" },
        basicUsername: { configured: false, source: "none" },
        basicPassword: { configured: false, source: "none" },
      },
    },
    llm: { activeProviderId: "fixture-provider", activeModel: "fixture-model", providers: [] },
    mesh: {
      enabled: false,
      mode: "lan",
      nodeId: "fixture-node",
      mdns: false,
      staticPeers: [],
      requireMtls: true,
      tailnetEnabled: false,
    },
    npu: {
      enabled: false,
      autoStart: false,
      sidecarUrl: "http://127.0.0.1:9000",
      status: {
        enabled: false,
        desiredState: "stopped",
        processState: "stopped",
        sidecarUrl: "http://127.0.0.1:9000",
        healthy: false,
        backend: "unknown",
        updatedAt: "2026-09-30T00:00:00.000Z",
        capability: {
          platform: "win32",
          arch: "x64",
          isWindowsArm64: false,
          onnxRuntimeAvailable: false,
          onnxRuntimeGenAiAvailable: false,
          qnnExecutionProviderAvailable: false,
          supported: false,
          details: [],
        },
      },
    },
    llamaCpp: {
      enabled: false,
      autoStart: false,
      managementMode: "external",
      baseUrl: "http://127.0.0.1:8080/v1",
      command: "",
      extraArgs: [],
      alias: "",
      status: {
        enabled: false,
        desiredState: "stopped",
        processState: "stopped",
        baseUrl: "http://127.0.0.1:8080/v1",
        healthy: false,
        updatedAt: "2026-09-30T00:00:00.000Z",
      },
    },
    features: {
      durableKernelV1Enabled: true,
      memoryMaintenanceV1Enabled: false,
      replayOverridesV1Enabled: false,
      memoryLifecycleAdminV1Enabled: false,
      memoryLifecycleAutoForgetEnabled: false,
      connectorDiagnosticsV1Enabled: false,
      computerUseGuardrailsV1Enabled: true,
      cronReviewQueueV1Enabled: false,
      replayRegressionV1Enabled: false,
    },
  };
}
