import type { ChannelSetupDefinition, ChannelSetupIssue } from "@goatcitadel/contracts";
import type { ChannelSetupRuntimeDefinition } from "./common.js";
import {
  requireCatalog,
  baseCatalogMeta,
  paragraph,
  note,
  check,
  readString,
  hasAnyConfiguredSecret,
  compactRecord,
  readLegacyString,
  requiredFieldIssue,
  malformedFieldIssue,
} from "./common.js";

export function createTeamsDefinition(): ChannelSetupRuntimeDefinition {
  const catalog = requireCatalog("channel.teams");
  const definition: ChannelSetupDefinition = {
    catalog: baseCatalogMeta(catalog, ["guided", "manual"]),
    wizard: {
      archetype: "webhook_destination",
      contentVersion: "2026.10.teams.workflows.v2",
      estimatedMinutes: 6,
      difficulty: "beginner",
      manualModePolicy: "available-secondary",
      introSummary: "Send outbound Adaptive Cards through a Microsoft Teams Workflows webhook.",
      prerequisites: [
        "Access to the target Teams channel.",
        "Permission to create a Workflows webhook with the Anyone trigger authentication option.",
        "A workflow owner and at least one co-owner who can maintain its Teams connection.",
      ],
      steps: [
        {
          id: "overview",
          kind: "intro",
          title: "What this connection does",
          body: [
            paragraph("GoatCitadel sends outbound Adaptive Cards through a Teams Workflows webhook. It does not install a conversational Teams bot."),
            note("warning", "Office 365 connector webhooks retired in May 2026. Create a Workflows webhook instead of a connector."),
            note(
              "warning",
              "Webhook URLs are secrets. Treat them like tokens and keep them out of committed config when possible.",
            ),
          ],
        },
        {
          id: "create-webhook",
          kind: "instruction",
          title: "Create the Teams workflow",
          body: [
            paragraph(
              "Open Workflows from the intended Teams channel. Create a flow with When a Teams webhook request is received and an action that posts the received Adaptive Card to that channel.",
            ),
            paragraph("Choose Anyone for trigger authentication. This adapter uses the signed webhook URL as its credential and sends no Microsoft Entra bearer token; tenant-only and specific-user triggers are unsupported."),
            paragraph("Confirm the workflow owner, add a co-owner, and keep the Teams action connection signed in. Workflows belong to users and can stop when their owner or connection becomes unavailable."),
          ],
          checklist: [
            check("channel", "Choose the intended Teams channel"),
            check("workflow", "Create the Adaptive Card workflow and select Anyone"),
            check("owner", "Confirm an owner and co-owner"),
            check("copied", "Copy the full webhook URL"),
          ],
        },
        {
          id: "collect-values",
          kind: "field-collection",
          title: "Paste your connection values",
          fields: [
            {
              key: "webhookUrl",
              label: "Webhook URL",
              type: "url",
              required: true,
              explanation: "The complete signed Workflows URL generated by the Anyone trigger. Treat the entire URL as a credential.",
              whyNeeded: "Used for every outbound message to the configured Teams channel.",
              whereToFind: [
                paragraph("Save the workflow and copy the complete HTTP POST URL from its webhook trigger, including its signature query parameters."),
              ],
              looksLike: "https://<environment>.environment.api.powerplatform.com/.../workflows/<id>/triggers/manual/paths/invoke?...",
              commonMistakes: ["Copying a Teams channel link or retired Office connector URL.", "Dropping signature query parameters.", "Selecting a tenant-only trigger that requires Microsoft Entra authentication."],
              sensitive: true,
              canChangeLater: true,
            },
            {
              key: "cardTitle",
              label: "Card title",
              type: "text",
              required: false,
              explanation: "Optional default title used for outbound Teams cards.",
              looksLike: "GoatCitadel",
              canChangeLater: true,
              placeholder: "GoatCitadel",
            },
          ],
        },
        {
          id: "test",
          kind: "test",
          title: "Validate the connection",
          body: [
            paragraph(
              "GoatCitadel validates the signed workflow URL shape and sends its Adaptive Card payload during guided test and retest flows. A valid URL alone does not prove compatibility.",
            ),
            paragraph("A successful HTTP response proves the workflow accepted the request. Check its run history and confirm the card arrived in the intended Teams channel before acknowledging the receipt."),
          ],
        },
        {
          id: "finish",
          kind: "confirm",
          title: "Finish setup",
          body: [
            paragraph(
              "After a successful sandbox send and confirmed receipt, review activation in Chat. Keep the workflow owner and co-owner able to maintain its Teams connection.",
            ),
          ],
          successCriteria: ["The Anyone Workflows URL is configured securely.", "A live sandbox card is confirmed in the intended Teams channel."],
        },
      ],
    },
    adapter: {
      adapterVersion: "2026.03.teams.v1",
      secretFieldKeys: ["webhookUrl"],
    },
    validation: {
      validationVersion: "2026.10.teams.workflows.v2",
      levels: ["structural", "semantic"],
    },
    testing: {
      testVersion: "2026.10.teams.workflows.v2",
      levels: ["structural", "semantic", "live-send", "manual-confirm"],
      safePreFinalize: true,
      supportsManualConfirmation: true,
    },
    troubleshooting: {
      commonFailures: [],
    },
    telemetry: {
      tier: "tier_2",
      namespace: "channel_setup.teams",
    },
    lifecycle: {
      supportedModes: ["create", "edit", "repair", "rotate_secret", "retest"],
      supportsDrafts: true,
      supportsEdit: true,
      supportsRepair: true,
      supportsRotateSecret: true,
      supportsRetest: true,
    },
    volatility: {
      officialDocsUrl:
        "https://support.microsoft.com/en-us/workflows/send-messages-in-teams-using-incoming-webhooks",
      lastReviewedAt: "2026-10-09",
      volatility: "medium",
      deprecationRisk: "high",
      preferredPathLabel: "Workflows webhook (Anyone)",
      legacyPathLabel: "Retired Office 365 connector",
    },
  };

  return {
    definition,
    hydrate(connection) {
      const config = connection.config;
      const hasConfiguredSecret = hasAnyConfiguredSecret(config, [["webhookUrl", "webhookUrlEnv"]]);
      return {
        draft: {
          cardTitle: readString(config, "cardTitle") ?? "GoatCitadel",
        },
        hydration: {
          status: hasConfiguredSecret ? "opaque-secret" : "clean",
          fieldState: {
            webhookUrl:
              readString(config, "webhookUrl") || readString(config, "webhookUrlEnv") ? "configured" : "missing",
            cardTitle: readString(config, "cardTitle") ? "configured" : "unknown",
          },
          warnings: hasConfiguredSecret
            ? [
                "Saved webhook URLs are intentionally not rehydrated into the wizard. Replace them only if you need to change them.",
              ]
            : [],
          rawLegacyConfig: config,
        },
      };
    },
    normalize(draft) {
      return compactRecord({
        // Do NOT fall back to webhookUrlEnv here: that copies the env-var NAME into the literal
        // webhookUrl field, which the runtime would then POST to verbatim. webhookUrlEnv is
        // preserved independently on the next line for env-backed delivery.
        webhookUrl: readString(draft.draft, "webhookUrl") ?? readLegacyString(draft, "webhookUrl"),
        webhookUrlEnv: readString(draft.draft, "webhookUrlEnv") ?? readLegacyString(draft, "webhookUrlEnv"),
        cardTitle: readString(draft.draft, "cardTitle") ?? "GoatCitadel",
      });
    },
    validate(draft) {
      const issues: ChannelSetupIssue[] = [];
      const webhookUrl = readString(draft.draft, "webhookUrl") ?? readLegacyString(draft, "webhookUrl");
      const hasConfiguredWebhook = Boolean(
        webhookUrl ||
        readString(draft.draft, "webhookUrlEnv") ||
        draft.hydration?.fieldState.webhookUrl === "configured",
      );
      if (!hasConfiguredWebhook) {
        issues.push(requiredFieldIssue("webhookUrl", "Webhook URL is required."));
      } else if (webhookUrl) {
        const kind = classifyTeamsWebhookUrl(webhookUrl);
        if (!kind) {
          issues.push(malformedFieldIssue("webhookUrl", "Use the complete HTTPS Teams Workflows trigger URL with its signature. Channel links, embedded login credentials and tenant-authenticated triggers are unsupported."));
        } else if (kind === "retired_connector") {
          issues.push({ key: "teams_retired_connector", fieldKey: "webhookUrl", level: draft.lifecycleMode === "create" ? "error" : "warn", failureCategory: "deprecated_path", message: "Office 365 connector webhooks retired in May 2026. Replace this saved URL with an Anyone Workflows webhook and run a live sandbox test." });
        } else if (kind === "legacy_workflow") {
          issues.push({ key: "teams_workflow_url_legacy", fieldKey: "webhookUrl", level: "info", failureCategory: "deprecated_path", message: "This is a legacy Logic Apps workflow URL. Copy the current URL from the flow designer; some environments migrated away from these URLs. Live acceptance and destination receipt are still required." });
        }
      }
      return issues;
    },
  };
}

/** Structural routing only: a live sandbox response and observed card receipt remain required. */
function classifyTeamsWebhookUrl(value: string): "workflow" | "legacy_workflow" | "retired_connector" | undefined {
  let url: URL;
  try { url = new URL(value); } catch { return undefined; }
  if (url.protocol !== "https:" || url.username || url.password || url.hash || (url.port && url.port !== "443")) return undefined;
  const hostname = url.hostname.toLowerCase();
  const label = "[a-z0-9](?:[a-z0-9-]*[a-z0-9])?";
  const microsoftSubdomain = (suffix: string) => new RegExp("^(?:" + label + "\\.)+" + suffix.replaceAll(".", "\\.") + "$", "i").test(hostname);
  if ((hostname === "outlook.office.com" || microsoftSubdomain("webhook.office.com")) && /^\/webhook(?:b2)?\/[^\s]+$/i.test(url.pathname)) return "retired_connector";
  if (url.searchParams.getAll("sig").length !== 1 || !url.searchParams.get("sig")?.trim()) return undefined;
  const invoke = "workflows/[a-z0-9-]{1,128}/triggers/manual/paths/invoke/?";
  if (microsoftSubdomain("environment.api.powerplatform.com") && new RegExp("^/powerautomate/automations/direct/(?:cu/[0-9]+/)?" + invoke + "$", "i").test(url.pathname)) return "workflow";
  if (microsoftSubdomain("logic.azure.com") && new RegExp("^/" + invoke + "$", "i").test(url.pathname)) return "legacy_workflow";
  return undefined;
}
