/** Integrations / channels domain slice. Pure re-exports from client.ts. */
export {
  fetchIntegrationCatalog,
  fetchChannelSetupDefinitions,
  fetchChannelSetupDefinition,
  fetchChannelSetupDrafts,
  createChannelSetupDraft,
  updateChannelSetupDraft,
  validateChannelSetupDraft,
  testChannelSetupDraft,
  finalizeChannelSetupDraft,
  createChannelRepairDraft,
  createChannelRotateSecretDraft,
  fetchChannelCapabilities,
  fetchChannelRuntimeStatus,
  fetchChannelDiagnostics,
  commsSend,
  commsReply,
  commsReact,
  commsUnsend,
  commsTyping,
  commsGmailRead,
  commsGmailSend,
  commsCalendarList,
  commsCalendarCreate,
} from "./client.js";
