/** Memory domain slice. Pure re-exports from client.ts. */
export {
  composeMemoryContext,
  fetchMemoryContext,
  fetchMemoryQmdStats,
  fetchMemoryItems,
  patchMemoryItem,
  forgetMemoryItem,
  fetchMemoryItemHistory,
  fetchMemoryMaintenancePolicy,
  patchMemoryMaintenancePolicy,
  fetchMemoryMaintenanceStatus,
  fetchMemoryMaintenanceRuns,
  runMemoryMaintenanceNow,
  fetchMemoryMaintenanceRunProvenance,
  fetchMemoryMaintenanceRecommendations,
  acceptMemoryMaintenanceRecommendation,
  rejectMemoryMaintenanceRecommendation,
  forgetMemory,
  fetchMemoryFiles,
  knowledgeMemoryWrite,
  knowledgeMemorySearch,
  knowledgeDocsIngest,
  knowledgeEmbeddingsIndex,
  knowledgeEmbeddingsQuery,
} from "./client.js";
