// Frozen forward migration. Preserve rows and all existing constraints.
// Rollback is restoration of the pre-migration backup; no narrowing conversion is supplied.
export const POSTGRES_SCHEMA_CONVERGENCE_V196_SQL = `
-- Forward-only convergence of additive INTEGER columns to canonical BIGINT.
ALTER TABLE "channel_delivery_parts" ALTER COLUMN "attempt" TYPE BIGINT;
ALTER TABLE "channel_delivery_parts" ALTER COLUMN "part_index" TYPE BIGINT;
ALTER TABLE "channel_delivery_parts" ALTER COLUMN "revision" TYPE BIGINT;
ALTER TABLE "memory_item_enumeration_state" ALTER COLUMN "singleton_id" TYPE BIGINT;
ALTER TABLE "permission_profile_selection_state" ALTER COLUMN "singleton_id" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_backing_capacity_observations" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_backing_capacity_observations" ALTER COLUMN "revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_backing_capacity_observations" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_capacity_inventories" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_capacity_inventories" ALTER COLUMN "capacity_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_capacity_inventories" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_capacity_inventories" ALTER COLUMN "execution_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_capacity_inventories" ALTER COLUMN "cleanup_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_capacity_inventories" ALTER COLUMN "backup_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_capacity_inventories" ALTER COLUMN "peak_inode_count" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_capacity_observations" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_capacity_observations" ALTER COLUMN "revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_capacity_observations" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_format_checkpoints" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_format_checkpoints" ALTER COLUMN "sequence" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_mount_checkpoints" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_mount_checkpoints" ALTER COLUMN "sequence" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_mounted_workspace_checkpoints" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_mounted_workspace_checkpoints" ALTER COLUMN "sequence" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_object_inventory_observations" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_object_inventory_observations" ALTER COLUMN "revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_object_inventory_observations" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_object_inventory_staging" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_object_inventory_staging" ALTER COLUMN "expected_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_object_inventory_staging" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_object_inventory_staging" ALTER COLUMN "execution_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_object_inventory_staging" ALTER COLUMN "cleanup_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_protection_checkpoints" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_protection_checkpoints" ALTER COLUMN "sequence" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_provisioning" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_provisioning" ALTER COLUMN "capacity_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_provisioning_checkpoints" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_provisioning_checkpoints" ALTER COLUMN "sequence" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_volume_checkpoints" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_cell_volume_checkpoints" ALTER COLUMN "sequence" TYPE BIGINT;
ALTER TABLE "remote_worker_chat_parent_recoveries" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_chat_parent_recoveries" ALTER COLUMN "recovery_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_chat_resume_recoveries" ALTER COLUMN "recovery_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_chat_resume_wakes" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_chat_resume_wakes" ALTER COLUMN "prior_lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_native_capacity_captures" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_native_capacity_captures" ALTER COLUMN "byte_length" TYPE BIGINT;
ALTER TABLE "remote_worker_native_capacity_deliveries" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_native_capacity_deliveries" ALTER COLUMN "capacity_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_native_capacity_pages" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_native_capacity_pages" ALTER COLUMN "page_offset" TYPE BIGINT;
ALTER TABLE "remote_worker_native_capacity_pages" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_native_file_receipts" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_native_file_receipts" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_native_file_transfer_pages" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_native_file_transfer_pages" ALTER COLUMN "file_index" TYPE BIGINT;
ALTER TABLE "remote_worker_native_file_transfer_pages" ALTER COLUMN "page_index" TYPE BIGINT;
ALTER TABLE "remote_worker_native_file_transfer_pages" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_native_file_transfers" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_native_file_transfers" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_native_policy_reservations" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_expectations" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_expectations" ALTER COLUMN "execution_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_expectations" ALTER COLUMN "cleanup_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_expectations" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_output_evidence" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_output_evidence" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_result_staging" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_result_staging" ALTER COLUMN "byte_length" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_result_staging" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_result_staging" ALTER COLUMN "execution_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_result_staging" ALTER COLUMN "cleanup_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_results" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_results" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_tool_budget_dispatches" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_install_outcomes" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_install_outcomes" ALTER COLUMN "lease_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_install_requests" ALTER COLUMN "assignment_generation" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_install_requests" ALTER COLUMN "execution_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_install_requests" ALTER COLUMN "cleanup_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_install_requests" ALTER COLUMN "capacity_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_install_requests" ALTER COLUMN "backup_revision" TYPE BIGINT;
ALTER TABLE "remote_worker_runtime_install_requests" ALTER COLUMN "lease_revision" TYPE BIGINT;

-- Retain equivalent existing constraint indexes; add canonical named indexes.
CREATE UNIQUE INDEX IF NOT EXISTS "idx_channel_delivery_parts_approval_id_unique" ON "channel_delivery_parts" ("approval_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_channel_delivery_parts_delivery_id_attempt_par_8be8b03aa0af" ON "channel_delivery_parts" ("delivery_id", "attempt", "part_index");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_channel_delivery_parts_provider_delivery_id_unique" ON "channel_delivery_parts" ("provider_delivery_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_remote_worker_cell_backing_capacity_observatio_dffbbf29e4c0" ON "remote_worker_cell_backing_capacity_observations" ("registry_workspace_id", "assignment_id", "assignment_generation", "connection_nonce_hex");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_remote_worker_cell_capacity_inventories_regist_6dcc1ec8a8db" ON "remote_worker_cell_capacity_inventories" ("registry_workspace_id", "assignment_id", "assignment_generation", "capture_sha256");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_remote_worker_cell_capacity_observations_regis_f08a09da47d1" ON "remote_worker_cell_capacity_observations" ("registry_workspace_id", "assignment_id", "assignment_generation", "connection_nonce_hex");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_remote_worker_cell_object_inventory_observatio_bf1d22d1f712" ON "remote_worker_cell_object_inventory_observations" ("registry_workspace_id", "assignment_id", "assignment_generation", "connection_nonce_hex");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_remote_worker_chat_resume_wakes_durable_run_id_65351a70fdd9" ON "remote_worker_chat_resume_wakes" ("durable_run_id", "waiting_checkpoint_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_remote_worker_chat_resume_wakes_registry_works_bb13c2b0fe2b" ON "remote_worker_chat_resume_wakes" ("registry_workspace_id", "assignment_id", "assignment_generation", "prior_lease_revision");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_remote_worker_chat_tasks_task_id_unique" ON "remote_worker_chat_tasks" ("task_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_remote_worker_native_capacity_captures_registr_d3c2b41b4376" ON "remote_worker_native_capacity_captures" ("registry_workspace_id", "assignment_id", "assignment_generation", "bundle_sha256");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_remote_worker_native_capacity_deliveries_regis_1c6da50a5d2d" ON "remote_worker_native_capacity_deliveries" ("registry_workspace_id", "assignment_id", "assignment_generation", "capacity_revision");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_remote_worker_native_capacity_deliveries_regis_c689c045d8e4" ON "remote_worker_native_capacity_deliveries" ("registry_workspace_id", "assignment_id", "assignment_generation", "capture_nonce");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_remote_worker_native_policy_reservations_decision_id_unique" ON "remote_worker_native_policy_reservations" ("decision_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_remote_worker_runtime_expectations_registry_wo_435fabb1d88f" ON "remote_worker_runtime_expectations" ("registry_workspace_id", "assignment_id", "assignment_generation", "execution_revision");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_remote_worker_runtime_install_requests_registr_472d63a97bf5" ON "remote_worker_runtime_install_requests" ("registry_workspace_id", "assignment_id", "assignment_generation", "nonce");

-- Preserve the intended descending pagination/time access paths across lineages.
DROP INDEX IF EXISTS idx_memory_items_enumeration;
CREATE INDEX idx_memory_items_enumeration ON memory_items(updated_at DESC, item_id DESC);
DROP INDEX IF EXISTS idx_tool_access_decisions_policy_time;
CREATE INDEX idx_tool_access_decisions_policy_time ON tool_access_decisions(policy_tool_name, timestamp DESC) WHERE policy_tool_name IS NOT NULL AND counts_toward_limits = 1;
`;
